language: python
python:
  - "2.6"
  - "2.7"
  - "pypy"
  - "3.2"
  - "3.3"
  - "3.4"

install:
  - "pip install -r requirements_dev.txt"
  - "pip install -e ."

script:
  - "python setup.py test"
  - "python setup.py develop"
  - "pip install ."
  - "py.test"

matrix:
  allow_failures:
    - python: "3.2"

notifications:
  email:
    on_success: change
    on_failure: always
